version: '3.8'

services:
  library-app:
    build: ./
    command: ./binary
    ports:
      - 5000:${PORT}
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_PARAM: ${POSTGRES_PARAM}
      POSTGRES_USER: ${POSTGRES_USER}
      PORT: ${PORT}

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s